version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: device-recycle-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: device_recycle
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/scripts/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # Redis缓存 (可选)
  redis:
    image: redis:7-alpine
    container_name: device-recycle-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Go后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: device-recycle-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASS=password
      - DB_NAME=device_recycle
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis
    volumes:
      - ./backend/uploads:/app/uploads

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: device-recycle-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist/build/h5:/usr/share/nginx/html
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
